name: Build and Test

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, reopened]
  workflow_dispatch:

concurrency:
  group: rust-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: cargo clippy -- -D warnings

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-args:
          - --all-features
          - --no-default-features --features alloc
          - --no-default-features
    steps:
      - uses: actions/checkout@v3
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Build
        run: cargo build ${{ matrix.feature-args }} --verbose
      - name: Test
        run: cargo test ${{ matrix.feature-args }} -- --nocapture
